"""
report_service/pdf_builder.py
Generates a PDF reconciliation report using ReportLab.

Report structure:
  Page 1 — Cover: Client name, GSTIN, period, generated date
  Page 2 — Executive Summary: Counts, ITC at risk, severity breakdown (table)
  Page 3+ — Mismatch Details: One section per severity group
  Last    — Footer on every page: "Confidential — generated by GST Reconciliation Agent"

Design choices:
  - Uses ReportLab's Platypus (document-layout engine) not canvas directly
  - Styles are defined once and reused — no inline magic numbers
  - Tables use alternating row colours for readability
  - All amounts in Indian number format (₹1,23,456.78)
"""

from __future__ import annotations

import io
import logging
from datetime import date, datetime
from typing import Any

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    BaseDocTemplate, Frame, PageTemplate,
    Paragraph, Spacer, Table, TableStyle, HRFlowable, PageBreak,
)

logger = logging.getLogger(__name__)

# ── Colour palette ─────────────────────────────────────────
NAVY      = colors.HexColor("#1a2744")
BLUE      = colors.HexColor("#2563eb")
LIGHT_BLUE = colors.HexColor("#dbeafe")
RED       = colors.HexColor("#dc2626")
AMBER     = colors.HexColor("#d97706")
GREEN     = colors.HexColor("#16a34a")
LIGHT_GREY = colors.HexColor("#f8fafc")
MID_GREY  = colors.HexColor("#e2e8f0")
DARK_GREY = colors.HexColor("#475569")
WHITE     = colors.white
BLACK     = colors.black

SEVERITY_COLOURS = {
    "escalate":  RED,
    "followup":  AMBER,
    "auto":      GREEN,
}

# ── Indian number formatter ────────────────────────────────
def fmt_inr(amount: float) -> str:
    if amount == 0:
        return "₹0.00"
    integer_part, decimal_part = f"{abs(amount):.2f}".split(".")
    n = len(integer_part)
    if n <= 3:
        result = integer_part
    else:
        result = integer_part[-3:]
        remaining = integer_part[:-3]
        while remaining:
            result = remaining[-2:] + "," + result
            remaining = remaining[:-2]
    sign = "-" if amount < 0 else ""
    return f"{sign}₹{result}.{decimal_part}"


# ── Page template with header/footer ──────────────────────

def _make_page_template(doc, firm_name: str):
    """Create a page template with header bar and footer on every page."""
    def _header_footer(canvas, doc):
        canvas.saveState()
        w, h = A4

        # Top header bar
        canvas.setFillColor(NAVY)
        canvas.rect(0, h - 20*mm, w, 20*mm, fill=1, stroke=0)
        canvas.setFillColor(WHITE)
        canvas.setFont("Helvetica-Bold", 11)
        canvas.drawString(15*mm, h - 13*mm, "GST Reconciliation Report")
        canvas.setFont("Helvetica", 9)
        canvas.drawRightString(w - 15*mm, h - 13*mm, firm_name)

        # Footer
        canvas.setFillColor(DARK_GREY)
        canvas.setFont("Helvetica", 8)
        canvas.drawString(15*mm, 10*mm, "Confidential — Generated by GST Reconciliation Agent")
        canvas.drawRightString(w - 15*mm, 10*mm, f"Page {doc.page}")
        canvas.restoreState()

    frame = Frame(
        15*mm, 20*mm,
        A4[0] - 30*mm, A4[1] - 40*mm,
        id="main"
    )
    return PageTemplate(id="main", frames=[frame], onPage=_header_footer)


# ── Styles ─────────────────────────────────────────────────

def _get_styles():
    base = getSampleStyleSheet()
    styles = {
        "title": ParagraphStyle(
            "title", fontName="Helvetica-Bold", fontSize=22,
            textColor=NAVY, spaceAfter=6, alignment=TA_CENTER,
        ),
        "subtitle": ParagraphStyle(
            "subtitle", fontName="Helvetica", fontSize=13,
            textColor=DARK_GREY, spaceAfter=4, alignment=TA_CENTER,
        ),
        "section": ParagraphStyle(
            "section", fontName="Helvetica-Bold", fontSize=13,
            textColor=NAVY, spaceBefore=12, spaceAfter=6,
        ),
        "body": ParagraphStyle(
            "body", fontName="Helvetica", fontSize=9,
            textColor=BLACK, spaceAfter=3, leading=13,
        ),
        "small": ParagraphStyle(
            "small", fontName="Helvetica", fontSize=8,
            textColor=DARK_GREY, spaceAfter=2,
        ),
        "bold": ParagraphStyle(
            "bold", fontName="Helvetica-Bold", fontSize=9,
            textColor=BLACK, spaceAfter=3,
        ),
        "amount": ParagraphStyle(
            "amount", fontName="Helvetica-Bold", fontSize=9,
            textColor=NAVY, alignment=TA_RIGHT,
        ),
        "risk": ParagraphStyle(
            "risk", fontName="Helvetica-Bold", fontSize=9,
            textColor=RED, alignment=TA_RIGHT,
        ),
    }
    return styles


# ── Table style builders ───────────────────────────────────

def _summary_table_style():
    return TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), NAVY),
        ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 9),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("ALIGN", (0, 0), (0, -1), "LEFT"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, LIGHT_GREY]),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 1), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.3, MID_GREY),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
    ])


def _mismatch_table_style():
    return TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), BLUE),
        ("TEXTCOLOR", (0, 0), (-1, 0), WHITE),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 8),
        ("ALIGN", (0, 0), (-1, 0), "CENTER"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, LIGHT_BLUE]),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 1), (-1, -1), 8),
        ("GRID", (0, 0), (-1, -1), 0.3, MID_GREY),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 5),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("WORDWRAP", (0, 0), (-1, -1), True),
    ])


# ── Public API ────────────────────────────────────────────

def build_pdf_report(
    client_name: str,
    client_gstin: str,
    filing_period: str,
    ca_name: str,
    firm_name: str,
    total_invoices: int,
    matched_count: int,
    auto_mismatches: list[dict],
    followup_mismatches: list[dict],
    escalation_mismatches: list[dict],
    total_itc_at_risk: float,
) -> bytes:
    """
    Generate a PDF reconciliation report and return it as bytes.

    Args:
        All report data — mismatches already classified by severity
    Returns:
        PDF file contents as bytes (write to file or upload to GCS)
    """
    buffer = io.BytesIO()

    doc = BaseDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=15*mm, rightMargin=15*mm,
        topMargin=22*mm, bottomMargin=22*mm,
    )
    doc.addPageTemplates([_make_page_template(doc, firm_name)])

    styles = _get_styles()
    story = []

    # ── Cover page ─────────────────────────────────────────
    story.append(Spacer(1, 20*mm))
    story.append(Paragraph("GST Reconciliation Report", styles["title"]))
    story.append(Paragraph(f"{client_name}", styles["subtitle"]))
    story.append(Paragraph(f"GSTIN: {client_gstin}", styles["subtitle"]))
    story.append(Paragraph(f"Filing Period: {filing_period}", styles["subtitle"]))
    story.append(Spacer(1, 4*mm))
    story.append(HRFlowable(width="100%", thickness=1, color=BLUE))
    story.append(Spacer(1, 4*mm))

    # Cover summary box
    cover_data = [
        ["Prepared by", firm_name],
        ["CA Name", ca_name],
        ["Generated on", datetime.now().strftime("%d %B %Y, %I:%M %p")],
        ["Total ITC at Risk", fmt_inr(total_itc_at_risk)],
    ]
    cover_table = Table(cover_data, colWidths=[50*mm, 110*mm])
    cover_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTNAME", (1, 0), (1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [WHITE, LIGHT_GREY]),
        ("GRID", (0, 0), (-1, -1), 0.3, MID_GREY),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("TEXTCOLOR", (1, 3), (1, 3), RED),
        ("FONTNAME", (1, 3), (1, 3), "Helvetica-Bold"),
    ]))
    story.append(cover_table)
    story.append(PageBreak())

    # ── Executive Summary ──────────────────────────────────
    story.append(Paragraph("Executive Summary", styles["section"]))
    story.append(HRFlowable(width="100%", thickness=0.5, color=MID_GREY))
    story.append(Spacer(1, 3*mm))

    total_mismatches = len(auto_mismatches) + len(followup_mismatches) + len(escalation_mismatches)
    summary_data = [
        ["Metric", "Count", "Details"],
        ["Total Invoices Analysed", str(total_invoices), "Tally / Zoho Books + GST Portal"],
        ["Clean Matches", str(matched_count), "Fully reconciled — no action required"],
        ["Auto-Resolved (Rounding)", str(len(auto_mismatches)), "Difference ≤ ₹1 — system handled"],
        ["Needs Supplier Follow-up", str(len(followup_mismatches)), "Email sent to supplier(s)"],
        ["Requires CA Review", str(len(escalation_mismatches)), "High ITC risk — action required"],
        ["Total Mismatches", str(total_mismatches), ""],
        ["Total ITC at Risk", fmt_inr(total_itc_at_risk), "Across all unresolved mismatches"],
    ]
    summary_table = Table(summary_data, colWidths=[70*mm, 30*mm, 70*mm])
    summary_table.setStyle(_summary_table_style())

    # Highlight escalation row
    if len(escalation_mismatches) > 0:
        esc_row = 5  # 0=header, 1=invoices, 2=clean, 3=auto, 4=followup, 5=escalation
        summary_table.setStyle(TableStyle([
            ("TEXTCOLOR", (0, esc_row), (-1, esc_row), RED),
            ("FONTNAME", (0, esc_row), (-1, esc_row), "Helvetica-Bold"),
        ]))

    story.append(summary_table)
    story.append(Spacer(1, 8*mm))

    # Severity legend
    legend_data = [
        ["🔴 Escalate", "High ITC risk (≥ ₹5,000) or missing invoice — CA must review"],
        ["🟡 Follow-up", "ITC risk < ₹5,000 — supplier email sent"],
        ["🟢 Auto", "Rounding difference ≤ ₹1 — resolved automatically"],
    ]
    legend_table = Table(legend_data, colWidths=[35*mm, 135*mm])
    legend_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]))
    story.append(legend_table)
    story.append(PageBreak())

    # ── Mismatch sections ──────────────────────────────────
    sections = [
        ("🔴 Escalation Mismatches — Requires Immediate CA Action", escalation_mismatches, RED),
        ("🟡 Follow-up Mismatches — Supplier Notified", followup_mismatches, AMBER),
        ("🟢 Auto-Resolved Mismatches", auto_mismatches, GREEN),
    ]

    for section_title, mismatches, colour in sections:
        if not mismatches:
            continue

        story.append(Paragraph(section_title, styles["section"]))
        story.append(HRFlowable(width="100%", thickness=1, color=colour))
        story.append(Spacer(1, 3*mm))

        table_data = [
            ["Invoice No", "Type", "Cause", "ITC Risk", "Action"],
        ]
        for m in mismatches:
            table_data.append([
                Paragraph(str(m.get("invoice_no") or "N/A"), styles["small"]),
                Paragraph(str(m.get("mismatch_type", "")).upper(), styles["small"]),
                Paragraph(str(m.get("cause_reasoning", ""))[:200], styles["small"]),
                Paragraph(fmt_inr(m.get("itc_risk_amount", 0)), styles["small"]),
                Paragraph(str(m.get("recommended_action", ""))[:150], styles["small"]),
            ])

        mismatch_table = Table(
            table_data,
            colWidths=[28*mm, 18*mm, 55*mm, 22*mm, 47*mm],
            repeatRows=1,
        )
        mismatch_table.setStyle(_mismatch_table_style())
        story.append(mismatch_table)
        story.append(Spacer(1, 6*mm))

    # ── Build PDF ──────────────────────────────────────────
    doc.build(story)
    return buffer.getvalue()
